#!/bin/sh
cd /var/www/back
mv .env.example .env
php artisan migrate
composer install
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
