#!/bin/sh
cd /var/www/back
cp .env.example .env
composer install
php artisan migrate
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
